"""Inline the shipped scene and panel styles into index.html.

The wallpaper ships as one self-contained index.html, but each style is kept as
its own file under styles/ so it can be read, diffed and tested on its own:

    styles/scenes/<id>.js      SCENES.<id>, see SCENE STYLES in index.html
    styles/hud/<id>.css        rules scoped under body.hud-<id>
    styles/hud/<id>.js         HUDS.<id>, optional canvas hooks

What ships is whatever the scene_style and hud_style combos in project.json
offer, so adding a style is two steps: put its file in styles/, add its option
to the combo, then run this. The generated blocks sit between marker comments
and are replaced wholesale on every run, so never edit them in index.html.

Each file becomes its own <style> or <script> element rather than being pasted
into the main script: that is how they were tested, a syntax error in one
cannot take the whole wallpaper down, and the main script's "use strict" does
not apply to code that was not written for it.

    python tools/inline_styles.py          rewrite index.html
    python tools/inline_styles.py --check  exit 1 if index.html is stale
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
PROJECT = ROOT / "project.json"
BUILTIN = {"waves", "classic"}   # defined in index.html itself

CSS_BEGIN = "<!-- STYLE CSS: generated by tools/inline_styles.py from styles/hud, edit there -->"
CSS_END = "<!-- /STYLE CSS -->"
JS_BEGIN = "<!-- STYLE SCRIPTS: generated by tools/inline_styles.py from styles/, edit there -->"
JS_END = "<!-- /STYLE SCRIPTS -->"


def shipped(prop):
    props = json.loads(PROJECT.read_text(encoding="utf-8"))["general"]["properties"]
    return [o["value"] for o in props[prop]["options"] if o["value"] not in BUILTIN]


def read(path, closer):
    text = path.read_text(encoding="utf-8").strip("\n")
    # an HTML parser ends the element at the first closing tag, wherever it is
    if re.search(r"</" + closer, text, re.I):
        sys.exit(f"{path} contains </{closer}, which would end the inlined element early")
    return text


def build():
    css, js = [], []
    for sid in shipped("scene_style"):
        f = ROOT / "styles" / "scenes" / f"{sid}.js"
        if not f.exists():
            sys.exit(f"scene_style offers '{sid}' but {f} does not exist")
        js.append(f'<script data-style="{sid}">\n{read(f, "script")}\n</script>')
    for hid in shipped("hud_style"):
        c = ROOT / "styles" / "hud" / f"{hid}.css"
        j = ROOT / "styles" / "hud" / f"{hid}.js"
        if not c.exists() and not j.exists():
            sys.exit(f"hud_style offers '{hid}' but styles/hud has no {hid}.css or {hid}.js")
        if c.exists():
            css.append(f'<style data-style="{hid}">\n{read(c, "style")}\n</style>')
        if j.exists():
            js.append(f'<script data-style="{hid}">\n{read(j, "script")}\n</script>')
    return css, js


def splice(html, begin, end, blocks, anchor):
    body = "\n".join([begin, *blocks, end])
    if begin in html:
        i, k = html.index(begin), html.index(end) + len(end)
        return html[:i] + body + html[k:]
    i = html.rindex(anchor)
    return html[:i] + body + "\n" + html[i:]


def main():
    css, js = build()
    old = INDEX.read_text(encoding="utf-8")
    new = splice(old, CSS_BEGIN, CSS_END, css, "</head>")
    new = splice(new, JS_BEGIN, JS_END, js, "</body>")
    if "--check" in sys.argv:
        sys.exit(0 if new == old else 1)
    if new != old:
        # newline="" keeps the file's own line endings; no BOM
        INDEX.write_text(new, encoding="utf-8", newline="")
    print(f"index.html: {len(css)} style block(s), {len(js)} script block(s)"
          + ("" if new != old else ", already current"))


if __name__ == "__main__":
    main()
